// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeWbKNTp1lbG0sa5PQLOAYlgcQzGjDNL4',
    appId: '1:1094958611666:web:2e912949fecbd180bf810b',
    messagingSenderId: '1094958611666',
    projectId: 'firestore-flutter-d84cc',
    authDomain: 'firestore-flutter-d84cc.firebaseapp.com',
    storageBucket: 'firestore-flutter-d84cc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOztMnfLo5avJpvHuHY7EBVmHGSBkDybs',
    appId: '1:1094958611666:android:b634278530d1e678bf810b',
    messagingSenderId: '1094958611666',
    projectId: 'firestore-flutter-d84cc',
    storageBucket: 'firestore-flutter-d84cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqQP3qAbPezfl-he--NxJ9dcJWsc104lo',
    appId: '1:1094958611666:ios:6c4886724ac0e86cbf810b',
    messagingSenderId: '1094958611666',
    projectId: 'firestore-flutter-d84cc',
    storageBucket: 'firestore-flutter-d84cc.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqQP3qAbPezfl-he--NxJ9dcJWsc104lo',
    appId: '1:1094958611666:ios:6c4886724ac0e86cbf810b',
    messagingSenderId: '1094958611666',
    projectId: 'firestore-flutter-d84cc',
    storageBucket: 'firestore-flutter-d84cc.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirestore',
  );
}
